bygge og vaskeskript i egne filer

diff --git a/auto/build b/auto/build
--- a/auto/build
+++ b/auto/build
@@ -1,17 +1,9 @@
 #!/bin/sh
 
-set -e
+set -e  # exit on error
 
-# Make includes.binary directory in case it doesn't exist
-# Needed by steps below..
-mkdir -p config/includes.binary
-
-# Make note of build date and place i /root and on install medium
-date > config/includes.chroot_after_packages/root/celleos_build_date
-cp config/includes.chroot_after_packages/root/celleos_build_date config/includes.binary/
-
-# Build user manual and place it on medium
-make -C brukermanual
-cp brukermanual/celleos2_brukermanual.pdf config/includes.binary/
+for f in auto/buildscripts/*.sh ; do
+  bash "$f"
+done
 
 lb build noauto "${@}"
